### PR TITLE
Rubocop clean up

### LINKED ISSUE #30: Chore: Clean up code
Consistently make improvements to code style to conform with our styleguide. (link in repo)

### PR DESCRIPTION
**Pull request by timkleier**
## Description
Added Rubocop (with dependencies) to Gemfile, cleaned up mainly Layout offenses. Fixed about half of the overall offenses

## Github Issue
Fixes #30 

## Definition of Done
- [ X ] This PR has appropriate test coverage.
- [ N/A ] Documentation has been updated. *(if needed)*

### CODE REVIEW

**Review by rebeccafae — COMMENTED** [review]
It has been a while since I have used rubocop, please remind me, when is rubocop run? Is there any documentation that should be added to the ReadMe about how to run it and see the errors?

**Comment by timkleier** [comment]
`rubocop` (with optional tags) can be run in conjunction with a test suite (before/after `rspec spec/`), and I believe it can also be integrated into Travis CI. I wasn't sure how extensively you wanted it used, so I just ran it a bunch and cleaned up some of the issues it produced. 

If you want it to be a standard for quality control in pull requests, we could just add a mention to run `rubocop` (see [documentation](https://rubocop.readthedocs.io/en/latest/)) and fix any issues before submitting a pull request.

**Comment by rebeccafae** [comment]
I think suggesting for people to run it before submitting a PR will be best for now, and once we get it all cleaned up we can add it to travis CI at that point. Thanks

**Comment by timkleier** [comment]
I added a note on the contributing.md file.

**Review by rebeccafae — APPROVED** [review]

**Comment by rebeccafae** [comment]
@timkleier it seems you have some conflicts. I can merge this once those are resolved.

**Comment by timkleier** [comment]
@rebeccafae, this should be good to go--a minor conflict I somehow missed.

**Pull request merged**
